version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/db/data

