name: Python testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          pip install --upgrade flask
          pip install --upgrade pytest
      - uses: actions/checkout@v3
      - name: Test with pytest
        run: | 
          pytest test_flask.py
          echo "The job executed with success"
        if: ${{ success() }}
