name: Python testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip -y
          pip install --upgrade flask
          pip install --upgrade pytest
      - uses: actions/checkout@v3
      - name: Test with pytest
        run: | 
          pytest test_flask.py
          echo "The job executed with success"
        if: ${{ success() }}
